version: '3.8'

services:
  api:
    build: .
    ports:
      - "8081:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

